### ISSUE TITLE
Bug: 分刀插件无法跨面

### ISSUE THREAD

**Issue by SaarChaffee** [SonderXiaoming/kanna_connection_redive#9]
当指定一个以上的阶段时就会报错。
指令：`分刀 ACC T 153`
```log

[2023-09-23 17:39:05,535 分刀] ERROR: <class 'UnboundLocalError'> occured when fen_dao handling message 114514.,
[2023-09-23 17:39:05,526 分刀] INFO: Message 1081809367 triggered fen_dao.,
[2023-09-23 17:39:05,526] INFO in msghandler: Message 114514 triggered fen_dao.,
[2023-09-23 17:39:05,535] ERROR in msghandler: <class 'UnboundLocalError'> occured when fen_dao handling message 114514.,
[2023-09-23 17:39:05,535 分刀] ERROR: local variable 'stage' referenced before assignment,
Traceback (most recent call last):,
  File "/HoshinoBot/hoshino/msghandler.py", line 23, in handle_message,
    await service_func.func(bot, event),
  File "/HoshinoBot/hoshino/modules/kanna_connection_redive/fendao/__init__.py", line 268, in fen_dao,
    result = await dao.fen_dao(),
  File "/HoshinoBot/hoshino/modules/kanna_connection_redive/fendao/timeaxis.py", line 263, in fen_dao,
    await self.get_work_list(works[0], boss, stage),
UnboundLocalError: local variable 'stage' referenced before assignment,

**Comment by SonderXiaoming** [comment]
等修
